services:
  db:
    container_name: dbbox
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./tmp/data/db:/data/db

  api:
    container_name: apibox
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8085:4001
    depends_on:
      - db
    env_file:
      - ../.env.local
    volumes:
      - ./tmp/data/api:/data/api


  web:
    container_name: webbox
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./tmp/data/web:/data/web